<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGlg8bav\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGlg8bav/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerGlg8bav.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerGlg8bav\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerGlg8bav\appProdProjectContainer([
    'container.build_hash' => 'Glg8bav',
    'container.build_id' => '039409d0',
    'container.build_time' => 1564368366,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGlg8bav');
